IF OBJECT_ID('Eventos_Peru.dbo.TBL_CLIENTE_EVENTO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_CLIENTE_EVENTO END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_ESTADO_EVENTO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_ESTADO_EVENTO END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_PROVEEDOR_EVENTO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_PROVEEDOR_EVENTO END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_EVENTO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_EVENTO END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_TIPO_EVENTO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_TIPO_EVENTO END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_USUARIO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_USUARIO END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_EMPRESA') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_EMPRESA END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_PERFIL') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_PERFIL END
IF OBJECT_ID('Eventos_Peru.dbo.TBL_TIPO_DOCUMENTO') != 0 BEGIN DROP TABLE Eventos_Peru.dbo.TBL_TIPO_DOCUMENTO END

CREATE TABLE Eventos_Peru.dbo.TBL_TIPO_DOCUMENTO(
	ID_TIPO_DOCUMENTO INT IDENTITY(1,1) PRIMARY KEY
	,TIPO_DOCUMENTO VARCHAR(50)
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_PERFIL(
	ID_PERFIL INT IDENTITY(1,1) PRIMARY KEY
	,PERFIL VARCHAR(80)
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_EMPRESA(
	ID_EMPRESA INT IDENTITY(1,1) PRIMARY KEY
	,ID_TIPO_DOCUMENTO INT REFERENCES TBL_TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO)
	,NUM_DOCUMENTO VARCHAR(25)
	,EMPRESA VARCHAR(80)
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_USUARIO (
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY
	,ID_TIPO_DOCUMENTO INT REFERENCES TBL_TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO)
	,NUM_DOCUMENTO VARCHAR(25)
	,NOMBRES VARCHAR(80)
	,P_APELLIDO VARCHAR(80)
	,M_APELLIDO VARCHAR(80)
	,CORREO VARCHAR(150)
	,ID_PERFIL INT REFERENCES TBL_PERFIL(ID_PERFIL)
	,ID_EMPRESA INT REFERENCES TBL_EMPRESA(ID_EMPRESA)
	,USUARIO VARCHAR(50)
	,CONTRASENA VARCHAR(255)
	,ID_ESTADO_REG TINYINT
)



CREATE TABLE Eventos_Peru.dbo.TBL_TIPO_EVENTO(
	ID_TIPO_EVENTO INT IDENTITY(1,1) PRIMARY KEY
	,TIPO_EVENTO VARCHAR(80)
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_EVENTO(
	ID_EVENTO INT IDENTITY(1,1) PRIMARY KEY
	,ID_TIPO_EVENTO INT REFERENCES TBL_TIPO_EVENTO(ID_TIPO_EVENTO)
	,DETALLE_EVENTO VARCHAR(800)
	,PRECIO FLOAT
	,RANGO_PRECIO FLOAT
	,IMAGEN VARCHAR(800)
	,FECHA_REGISTRO DATETIME
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_PROVEEDOR_EVENTO(
	ID_PROVEEDOR_EVENTO INT IDENTITY(1,1) PRIMARY KEY
	,ID_EVENTO INT REFERENCES TBL_EVENTO(ID_EVENTO)
	,ID_USUARIO_PROVEEDOR INT REFERENCES TBL_USUARIO(ID_USUARIO)
	,PRECIO FLOAT
	,FECHA_REGISTRO DATETIME
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_ESTADO_EVENTO(
	ID_ESTADO_EVENTO INT IDENTITY(1,1) PRIMARY KEY
	,ESTADO VARCHAR(80)
	,ID_ESTADO_REG TINYINT
)

CREATE TABLE Eventos_Peru.dbo.TBL_CLIENTE_EVENTO(
	ID_CLIENTE_EVENTO INT IDENTITY(1,1) PRIMARY KEY
	,ID_PROVEEDOR_EVENTO INT REFERENCES TBL_PROVEEDOR_EVENTO(ID_PROVEEDOR_EVENTO)
	,FECHA_REGISTRO DATETIME
	,FECHA_AGENDA DATE
	,HORA_AGENDA TIME
	,ID_USUARIO_CLIENTE INT REFERENCES TBL_USUARIO(ID_USUARIO)
	,ID_ESTADO_EVENTO INT REFERENCES TBL_ESTADO_EVENTO(ID_ESTADO_EVENTO)
	,PUNTUACION INT
	,COMENTARIO VARCHAR(300)
	,ID_ESTADO_REG TINYINT
)

INSERT INTO Eventos_Peru.dbo.TBL_TIPO_DOCUMENTO (TIPO_DOCUMENTO,ID_ESTADO_REG)
VALUES 
('DNI',1),
('RUC',1)

INSERT INTO Eventos_Peru.dbo.TBL_PERFIL (PERFIL,ID_ESTADO_REG)
VALUES 
('ADMINISTRADOR',1),
('USUARIO',1),
('CLIENTE',1),
('PROVEEDOR',1)

TRUNCATE TABLE Eventos_Peru.dbo.TBL_EMPRESA
INSERT INTO Eventos_Peru.dbo.TBL_EMPRESA (ID_TIPO_DOCUMENTO,EMPRESA,ID_ESTADO_REG)
VALUES 
('1','NO TIENE EMPRESA',1),
('2','EVENTOS PERU SAC',1),
('2','GESTIONAR SAC',1),
('2','GRUPO GLOBO SAC',1)

INSERT INTO Eventos_Peru.dbo.TBL_USUARIO(ID_TIPO_DOCUMENTO,NUM_DOCUMENTO,NOMBRES,P_APELLIDO,M_APELLIDO,CORREO,ID_PERFIL,ID_EMPRESA,USUARIO,CONTRASENA,ID_ESTADO_REG)
VALUES 
(1,'11111111','JOTA','JOTA','','ROOT@EJEMPLO.COM',1,2,'ROOT','1234',1),
(1,'22222222','MARIA','ALVAEZ','MEDINA','MARIA@EJEMPLO.COM',3,3,'MARIA','1234',1),
(1,'33333333','LUIS','SOTO','LOPEZ','LUIS@EJEMPLO.COM',4,4,'CARLOS','1234',1)
